spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taProntoDB?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
jwt:
  secret: its-ready-0.0.1
  expiration-minutes: 1

