server:
  port: 5000
spring:
  datasource:
    url: jdbc:postgresql://itsreadydb.ctskp4ncwsbu.us-east-1.rds.amazonaws.com:5432/itsreadydb
    username: postgres
    password: taProntoDBDeploy
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
jwt:
  secret: its-ready-0.0.1
  token:
    expiration-minutes: 1
  refresh-token:
    expiration-minutes: 1440