name: CI
on:
  pull_request:
    branches:    
      - master
      - 'releases/**'
  push:
    branches:
      - ci-cd
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build and test
        working-directory: ./back-end/TaProntoAPI
        run: mvn clean install
